//EntityType AutoGenerated by tool
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace API_SALES_ORDER_SRV
{

    public class A_SalesOrderItemTextType : BaseDTOWithIDAndETag
    {
        private string _SalesOrder;
        public string SalesOrder 
        { 
            get {
                return _SalesOrder;
            }
            set {
                if(value == null)
                {
                    throw new ValidationException("SalesOrder cannot be null and must have a value.");
                }
                if(value.Length > 10)
                {
                    throw new ValidationException("SalesOrder cannot be longer than 10 characters.");
                }
                else
                {
                    _SalesOrder = value;
                }
            }
        }
        private string _SalesOrderItem;
        public string SalesOrderItem 
        { 
            get {
                return _SalesOrderItem;
            }
            set {
                if(value == null)
                {
                    throw new ValidationException("SalesOrderItem cannot be null and must have a value.");
                }
                if(value.Length > 6)
                {
                    throw new ValidationException("SalesOrderItem cannot be longer than 6 characters.");
                }
                else
                {
                    _SalesOrderItem = value;
                }
            }
        }
        private string _Language;
        public string Language 
        { 
            get {
                return _Language;
            }
            set {
                if(value == null)
                {
                    throw new ValidationException("Language cannot be null and must have a value.");
                }
                if(value.Length > 2)
                {
                    throw new ValidationException("Language cannot be longer than 2 characters.");
                }
                else
                {
                    _Language = value;
                }
            }
        }
        private string _LongTextID;
        public string LongTextID 
        { 
            get {
                return _LongTextID;
            }
            set {
                if(value == null)
                {
                    throw new ValidationException("LongTextID cannot be null and must have a value.");
                }
                if(value.Length > 4)
                {
                    throw new ValidationException("LongTextID cannot be longer than 4 characters.");
                }
                else
                {
                    _LongTextID = value;
                }
            }
        }
        private string _LongText;
        public string LongText 
        { 
            get { 
                return _LongText;
            }
            set {
                if(value == null)
                {
                    throw new ValidationException("LongText cannot be null and must have a value.");
                }
                else
                {
                    _LongText = value;
                }
            }
        }
        
        public Deferred<API_SALES_ORDER_SRV.A_SalesOrderType> to_SalesOrder {get; set;}


        public Deferred<API_SALES_ORDER_SRV.A_SalesOrderItemType> to_SalesOrderItem {get; set;}


        protected override Dictionary<string, List<string>> ReferenceKeys 
        {   
            get 
            {
                var result = new Dictionary<string, List<string>>();
                result.Add("PrimaryKey", new List<string>() {"SalesOrder","SalesOrderItem","Language","LongTextID"});
                result.Add("to_SalesOrder", new List<string>() {"SalesOrder","SalesOrderItem","Language","LongTextID"});
                result.Add("to_SalesOrderItem", new List<string>() {"SalesOrder","SalesOrderItem","Language","LongTextID"});

                return result;
            }
        }


    }
}
