//EntitySet Generated by tool
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace API_SALES_ORDER_SRV
{

    public class A_SalesOrderItemText : ODataEntitySetOperations<API_SALES_ORDER_SRV.A_SalesOrderItemTextType>
    {
        public A_SalesOrderItemText(IOperationsDispatcher dispatcher) : base(dispatcher)
        {
        }

    }
}
