//EntitySet Generated by tool
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace API_SALES_ORDER_SRV
{

    public class A_SalesOrderItemRelatedObject : ODataEntitySetOperations<API_SALES_ORDER_SRV.A_SalesOrderItemRelatedObjectType>
    {
        public A_SalesOrderItemRelatedObject(IOperationsDispatcher dispatcher) : base(dispatcher)
        {
        }

    }
}
