//EntitySet Generated by tool
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace API_SALES_ORDER_SRV
{

    public class A_SalesOrderItem : ODataEntitySetOperations<API_SALES_ORDER_SRV.A_SalesOrderItemType>
    {
        public A_SalesOrderItem(IOperationsDispatcher dispatcher) : base(dispatcher)
        {
        }

    }
}
