//ComplexType Generated by tool
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace API_SALES_ORDER_SRV
{

    public class FunctionResult : BaseDTOWithIDAndETag
    {
        public Edm.Boolean Boolean { get; set; }

    }
}
