//AutoGenerated Code
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace API_SALES_ORDER_SRV
{

    public class ServiceRootSet : ODataEntitySetOperations<ServiceRoot>
    {
        public ServiceRootSet(IOperationsDispatcher dispatcher) : base(dispatcher)
        {
        }
        public async Task<API_SALES_ORDER_SRV.FunctionResult> rejectApprovalRequestAsync(string SalesOrder)
        {
            return (API_SALES_ORDER_SRV.FunctionResult) await _dispatcher.ExecuteFunctionImportAsync<API_SALES_ORDER_SRV.FunctionResult>(
                "rejectApprovalRequest", 
                new Dictionary<string, object>(){{"SalesOrder", SalesOrder}}
            );
        }
        public async Task<API_SALES_ORDER_SRV.FunctionResult> releaseApprovalRequestAsync(string SalesOrder)
        {
            return (API_SALES_ORDER_SRV.FunctionResult) await _dispatcher.ExecuteFunctionImportAsync<API_SALES_ORDER_SRV.FunctionResult>(
                "releaseApprovalRequest", 
                new Dictionary<string, object>(){{"SalesOrder", SalesOrder}}
            );
        }

    }
}
