//EntitySet Generated by tool
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace GWSAMPLE_BASIC
{

    public class BusinessPartnerSet : ODataEntitySetOperations<GWSAMPLE_BASIC.BusinessPartner>
    {
        public BusinessPartnerSet(IOperationsDispatcher dispatcher) : base(dispatcher)
        {
        }

    }
}
