//EntitySet Generated by tool
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace GWSAMPLE_BASIC
{

    public class ContactSet : ODataEntitySetOperations<GWSAMPLE_BASIC.Contact>
    {
        public ContactSet(IOperationsDispatcher dispatcher) : base(dispatcher)
        {
        }

    }
}
