//ComplexType Generated by tool
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace GWSAMPLE_BASIC
{

    public class CT_String : BaseDTOWithIDAndETag
    {
        private string _String;
        public string String 
        { 
            get { 
                return _String;
            }
            set {
                if(value == null)
                {
                    throw new ValidationException("String cannot be null and must have a value.");
                }
                else
                {
                    _String = value;
                }
            }
        }
        

    }
}
