//AutoGenerated Code
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace GWSAMPLE_BASIC
{

    public static class DISetup
    {
        public static IServiceCollection RegisterSetsAsSingletons(this IServiceCollection services)
        {
            services.AddSingleton<ServiceRootSet>();
            services.AddSingleton<BusinessPartnerSet>();
            services.AddSingleton<ProductSet>();
            services.AddSingleton<SalesOrderSet>();
            services.AddSingleton<SalesOrderLineItemSet>();
            services.AddSingleton<ContactSet>();
            services.AddSingleton<VH_SexSet>();
            services.AddSingleton<VH_CountrySet>();
            services.AddSingleton<VH_AddressTypeSet>();
            services.AddSingleton<VH_CategorySet>();
            services.AddSingleton<VH_CurrencySet>();
            services.AddSingleton<VH_UnitQuantitySet>();
            services.AddSingleton<VH_UnitWeightSet>();
            services.AddSingleton<VH_UnitLengthSet>();
            services.AddSingleton<VH_ProductTypeCodeSet>();
            services.AddSingleton<VH_BPRoleSet>();
            services.AddSingleton<VH_LanguageSet>();
            return services;
        }
    }
}
