//EntitySet Generated by tool
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace GWSAMPLE_BASIC
{

    public class SalesOrderSet : ODataEntitySetOperations<GWSAMPLE_BASIC.SalesOrder>
    {
        public SalesOrderSet(IOperationsDispatcher dispatcher) : base(dispatcher)
        {
        }
        public async Task<GWSAMPLE_BASIC.SalesOrder> SalesOrder_ConfirmAsync(string SalesOrderID)
        {
            return (GWSAMPLE_BASIC.SalesOrder) await _dispatcher.ExecuteFunctionImportAsync<GWSAMPLE_BASIC.SalesOrder>(
                "SalesOrder_Confirm", 
                new Dictionary<string, object>(){{"SalesOrderID", SalesOrderID}}
            );
        }
        public async Task<GWSAMPLE_BASIC.SalesOrder> SalesOrder_CancelAsync(string SalesOrderID)
        {
            return (GWSAMPLE_BASIC.SalesOrder) await _dispatcher.ExecuteFunctionImportAsync<GWSAMPLE_BASIC.SalesOrder>(
                "SalesOrder_Cancel", 
                new Dictionary<string, object>(){{"SalesOrderID", SalesOrderID}}
            );
        }
        public async Task<GWSAMPLE_BASIC.SalesOrder> SalesOrder_InvoiceCreatedAsync(string SalesOrderID)
        {
            return (GWSAMPLE_BASIC.SalesOrder) await _dispatcher.ExecuteFunctionImportAsync<GWSAMPLE_BASIC.SalesOrder>(
                "SalesOrder_InvoiceCreated", 
                new Dictionary<string, object>(){{"SalesOrderID", SalesOrderID}}
            );
        }
        public async Task<GWSAMPLE_BASIC.SalesOrder> SalesOrder_GoodsIssueCreatedAsync(string SalesOrderID)
        {
            return (GWSAMPLE_BASIC.SalesOrder) await _dispatcher.ExecuteFunctionImportAsync<GWSAMPLE_BASIC.SalesOrder>(
                "SalesOrder_GoodsIssueCreated", 
                new Dictionary<string, object>(){{"SalesOrderID", SalesOrderID}}
            );
        }

    }
}
