//AutoGenerated Code
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace GWSAMPLE_BASIC
{

    public class ServiceRootSet : ODataEntitySetOperations<ServiceRoot>
    {
        public ServiceRootSet(IOperationsDispatcher dispatcher) : base(dispatcher)
        {
        }
        public async Task<GWSAMPLE_BASIC.CT_String> RegenerateAllDataAsync(int NoOfSalesOrders)
        {
            return (GWSAMPLE_BASIC.CT_String) await _dispatcher.ExecuteFunctionImportAsync<GWSAMPLE_BASIC.CT_String>(
                "RegenerateAllData", 
                new Dictionary<string, object>(){{"NoOfSalesOrders", NoOfSalesOrders}}
            );
        }

    }
}
