//EntitySet Generated by tool
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace GWSAMPLE_BASIC
{

    public class VH_AddressTypeSet : ODataEntitySetOperations<GWSAMPLE_BASIC.VH_AddressType>
    {
        public VH_AddressTypeSet(IOperationsDispatcher dispatcher) : base(dispatcher)
        {
        }

    }
}
