//EntitySet Generated by tool
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace GWSAMPLE_BASIC
{

    public class VH_BPRoleSet : ODataEntitySetOperations<GWSAMPLE_BASIC.VH_BPRole>
    {
        public VH_BPRoleSet(IOperationsDispatcher dispatcher) : base(dispatcher)
        {
        }

    }
}
