//EntityType AutoGenerated by tool
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace GWSAMPLE_BASIC
{

    public class VH_BPRole : BaseDTOWithIDAndETag
    {
        private string _BpRole;
        public string BpRole 
        { 
            get {
                return _BpRole;
            }
            set {
                if(value == null)
                {
                    throw new ValidationException("BpRole cannot be null and must have a value.");
                }
                if(value.Length > 3)
                {
                    throw new ValidationException("BpRole cannot be longer than 3 characters.");
                }
                else
                {
                    _BpRole = value;
                }
            }
        }
        private string _Shorttext;
        public string Shorttext 
        { 
            get {
                return _Shorttext;
            }
            set {
                if(value == null)
                {
                    throw new ValidationException("Shorttext cannot be null and must have a value.");
                }
                if(value.Length > 60)
                {
                    throw new ValidationException("Shorttext cannot be longer than 60 characters.");
                }
                else
                {
                    _Shorttext = value;
                }
            }
        }
        protected override Dictionary<string, List<string>> ReferenceKeys 
        {   
            get 
            {
                var result = new Dictionary<string, List<string>>();
                result.Add("PrimaryKey", new List<string>() {"BpRole"});

                return result;
            }
        }


    }
}
