//EntityType AutoGenerated by tool
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace GWSAMPLE_BASIC
{

    public class VH_Currency : BaseDTOWithIDAndETag
    {
        private string _Waers;
        public string Waers 
        { 
            get {
                return _Waers;
            }
            set {
                if(value == null)
                {
                    throw new ValidationException("Waers cannot be null and must have a value.");
                }
                if(value.Length > 5)
                {
                    throw new ValidationException("Waers cannot be longer than 5 characters.");
                }
                else
                {
                    _Waers = value;
                }
            }
        }
        private string _Ltext;
        public string Ltext 
        { 
            get {
                return _Ltext;
            }
            set {
                if(value == null)
                {
                    throw new ValidationException("Ltext cannot be null and must have a value.");
                }
                if(value.Length > 40)
                {
                    throw new ValidationException("Ltext cannot be longer than 40 characters.");
                }
                else
                {
                    _Ltext = value;
                }
            }
        }
        protected override Dictionary<string, List<string>> ReferenceKeys 
        {   
            get 
            {
                var result = new Dictionary<string, List<string>>();
                result.Add("PrimaryKey", new List<string>() {"Waers"});

                return result;
            }
        }


    }
}
