//EntityType AutoGenerated by tool
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace GWSAMPLE_BASIC
{

    public class VH_Country : BaseDTOWithIDAndETag
    {
        private string _Land1;
        public string Land1 
        { 
            get {
                return _Land1;
            }
            set {
                if(value == null)
                {
                    throw new ValidationException("Land1 cannot be null and must have a value.");
                }
                if(value.Length > 3)
                {
                    throw new ValidationException("Land1 cannot be longer than 3 characters.");
                }
                else
                {
                    _Land1 = value;
                }
            }
        }
        private string _Landx;
        public string Landx 
        { 
            get {
                return _Landx;
            }
            set {
                if(value == null)
                {
                    throw new ValidationException("Landx cannot be null and must have a value.");
                }
                if(value.Length > 15)
                {
                    throw new ValidationException("Landx cannot be longer than 15 characters.");
                }
                else
                {
                    _Landx = value;
                }
            }
        }
        private string _Natio;
        public string Natio 
        { 
            get {
                return _Natio;
            }
            set {
                if(value == null)
                {
                    throw new ValidationException("Natio cannot be null and must have a value.");
                }
                if(value.Length > 15)
                {
                    throw new ValidationException("Natio cannot be longer than 15 characters.");
                }
                else
                {
                    _Natio = value;
                }
            }
        }
        protected override Dictionary<string, List<string>> ReferenceKeys 
        {   
            get 
            {
                var result = new Dictionary<string, List<string>>();
                result.Add("PrimaryKey", new List<string>() {"Land1"});

                return result;
            }
        }


    }
}
