//EntitySet Generated by tool
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace GWSAMPLE_BASIC
{

    public class VH_CurrencySet : ODataEntitySetOperations<GWSAMPLE_BASIC.VH_Currency>
    {
        public VH_CurrencySet(IOperationsDispatcher dispatcher) : base(dispatcher)
        {
        }

    }
}
