//EntitySet Generated by tool
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace GWSAMPLE_BASIC
{

    public class VH_CategorySet : ODataEntitySetOperations<GWSAMPLE_BASIC.VH_Category>
    {
        public VH_CategorySet(IOperationsDispatcher dispatcher) : base(dispatcher)
        {
        }

    }
}
