//EntitySet Generated by tool
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace GWSAMPLE_BASIC
{

    public class VH_LanguageSet : ODataEntitySetOperations<GWSAMPLE_BASIC.VH_Language>
    {
        public VH_LanguageSet(IOperationsDispatcher dispatcher) : base(dispatcher)
        {
        }

    }
}
