//EntitySet Generated by tool
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace GWSAMPLE_BASIC
{

    public class VH_ProductTypeCodeSet : ODataEntitySetOperations<GWSAMPLE_BASIC.VH_ProductTypeCode>
    {
        public VH_ProductTypeCodeSet(IOperationsDispatcher dispatcher) : base(dispatcher)
        {
        }

    }
}
