//EntityType AutoGenerated by tool
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace GWSAMPLE_BASIC
{

    public class VH_ProductTypeCode : BaseDTOWithIDAndETag
    {
        private string _TypeCode;
        public string TypeCode 
        { 
            get {
                return _TypeCode;
            }
            set {
                if(value == null)
                {
                    throw new ValidationException("TypeCode cannot be null and must have a value.");
                }
                if(value.Length > 2)
                {
                    throw new ValidationException("TypeCode cannot be longer than 2 characters.");
                }
                else
                {
                    _TypeCode = value;
                }
            }
        }
        private string _Shorttext;
        public string Shorttext 
        { 
            get {
                return _Shorttext;
            }
            set {
                if(value == null)
                {
                    throw new ValidationException("Shorttext cannot be null and must have a value.");
                }
                if(value.Length > 60)
                {
                    throw new ValidationException("Shorttext cannot be longer than 60 characters.");
                }
                else
                {
                    _Shorttext = value;
                }
            }
        }
        protected override Dictionary<string, List<string>> ReferenceKeys 
        {   
            get 
            {
                var result = new Dictionary<string, List<string>>();
                result.Add("PrimaryKey", new List<string>() {"TypeCode"});

                return result;
            }
        }


    }
}
