//EntitySet Generated by tool
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace GWSAMPLE_BASIC
{

    public class VH_SexSet : ODataEntitySetOperations<GWSAMPLE_BASIC.VH_Sex>
    {
        public VH_SexSet(IOperationsDispatcher dispatcher) : base(dispatcher)
        {
        }

    }
}
