//EntitySet Generated by tool
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace GWSAMPLE_BASIC
{

    public class VH_UnitQuantitySet : ODataEntitySetOperations<GWSAMPLE_BASIC.VH_UnitQuantity>
    {
        public VH_UnitQuantitySet(IOperationsDispatcher dispatcher) : base(dispatcher)
        {
        }

    }
}
