//EntitySet Generated by tool
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace GWSAMPLE_BASIC
{

    public class VH_UnitWeightSet : ODataEntitySetOperations<GWSAMPLE_BASIC.VH_UnitWeight>
    {
        public VH_UnitWeightSet(IOperationsDispatcher dispatcher) : base(dispatcher)
        {
        }

    }
}
