//EntitySet Generated by tool
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace GWSAMPLE_BASIC
{

    public class VH_UnitLengthSet : ODataEntitySetOperations<GWSAMPLE_BASIC.VH_UnitLength>
    {
        public VH_UnitLengthSet(IOperationsDispatcher dispatcher) : base(dispatcher)
        {
        }

    }
}
