//EntitySet Generated by tool
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace API_PURCHASEORDER_PROCESS_SRV
{

    public class A_POSubcontractingComponent : ODataEntitySetOperations<API_PURCHASEORDER_PROCESS_SRV.A_POSubcontractingComponentType>
    {
        public A_POSubcontractingComponent(IOperationsDispatcher dispatcher) : base(dispatcher)
        {
        }

    }
}
