//EntitySet Generated by tool
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace API_PURCHASEORDER_PROCESS_SRV
{

    public class A_PurchaseOrderItemNote : ODataEntitySetOperations<API_PURCHASEORDER_PROCESS_SRV.A_PurchaseOrderItemNoteType>
    {
        public A_PurchaseOrderItemNote(IOperationsDispatcher dispatcher) : base(dispatcher)
        {
        }

    }
}
