//EntitySet Generated by tool
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace API_PURCHASEORDER_PROCESS_SRV
{

    public class A_PurchaseOrderScheduleLine : ODataEntitySetOperations<API_PURCHASEORDER_PROCESS_SRV.A_PurchaseOrderScheduleLineType>
    {
        public A_PurchaseOrderScheduleLine(IOperationsDispatcher dispatcher) : base(dispatcher)
        {
        }

    }
}
