//AutoGenerated Code
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace API_PURCHASEORDER_PROCESS_SRV
{

    public static class DISetup
    {
        public static IServiceCollection RegisterSetsAsSingletons(this IServiceCollection services)
        {
            services.AddSingleton<ServiceRootSet>();
            services.AddSingleton<A_POSubcontractingComponent>();
            services.AddSingleton<A_PurchaseOrder>();
            services.AddSingleton<A_PurchaseOrderItem>();
            services.AddSingleton<A_PurchaseOrderItemNote>();
            services.AddSingleton<A_PurchaseOrderNote>();
            services.AddSingleton<A_PurchaseOrderScheduleLine>();
            services.AddSingleton<A_PurOrdAccountAssignment>();
            services.AddSingleton<A_PurOrdPricingElement>();
            return services;
        }
    }
}
