//AutoGenerated Code
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace API_PURCHASEORDER_PROCESS_SRV
{

    public class ServiceRoot : BaseDTOWithIDAndETag
    {

    }
}
