//AutoGenerated Code
using Microsoft.Extensions.DependencyInjection;
using System.ComponentModel.DataAnnotations;
using DataOperations.OData; 
using DataOperations; 

namespace API_PURCHASEORDER_PROCESS_SRV
{

    public class ServiceRootSet : ODataEntitySetOperations<ServiceRoot>
    {
        public ServiceRootSet(IOperationsDispatcher dispatcher) : base(dispatcher)
        {
        }

    }
}
